server:
  port: 8085

cloud:
  eureka-host: localhost

spring:
  application:
    name: currency-service

currency:
  client:
    url: "http://www.cbr.ru/scripts/XML_daily.asp"

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka