server:
  port: 8090

cloud:
  eureka-host: localhost

spring:
  application:
    name: exchange-processing-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${cloud.eureka-host}:5432/processing
    username: postgres
    password: masterkey
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: false
    locations: classpath:db

service:
  currency:
    url: http://localhost:8085

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

